application: zxing
version: 2
runtime: python
api_version: 1

handlers:
- url: /generator
  script: redirect.py

- url: /scan
  static_files: site/scan.html
  upload: site/scan.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: (.*)/
  static_files: site\1/index.html
  upload: site/index.html

- url: /
  static_dir: site
