/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void sdrScale_change(GSlider source, GEvent event) { //_CODE_:sdrScale:786162:
   world.scale(source.getValueF());
} //_CODE_:sdrScale:786162:

public void option1_clicked1(GOption source, GEvent event) { //_CODE_:option1:504384:
  watchPatrol(0);
} //_CODE_:option1:504384:

public void option2_clicked1(GOption source, GEvent event) { //_CODE_:option2:556038:
  watchPatrol(1);
} //_CODE_:option2:556038:

public void option3_clicked1(GOption source, GEvent event) { //_CODE_:option3:503628:
  watchPatrol(2);
} //_CODE_:option3:503628:

public void option4_clicked1(GOption source, GEvent event) { //_CODE_:option4:531075:
  watchPatrol(3);
} //_CODE_:option4:531075:

public void option5_clicked1(GOption source, GEvent event) { //_CODE_:option5:629051:
  watchPatrol(4);
} //_CODE_:option5:629051:

public void option6_clicked1(GOption source, GEvent event) { //_CODE_:option6:288050:
  watchPatrol(5);
} //_CODE_:option6:288050:

public void option7_clicked1(GOption source, GEvent event) { //_CODE_:option7:545917:
  watchPatrol(6);
} //_CODE_:option7:545917:

public void option8_clicked1(GOption source, GEvent event) { //_CODE_:option8:854451:
  watchPatrol(7);
} //_CODE_:option8:854451:

public void option9_clicked1(GOption source, GEvent event) { //_CODE_:option9:936626:
  watchPatrol(8);
} //_CODE_:option9:936626:

public void option10_clicked1(GOption source, GEvent event) { //_CODE_:option10:581130:
  watchPatrol(-1);
} //_CODE_:option10:581130:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.PURPLE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  sdrScale = new GSlider(this, 510, 10, 460, 20, 10.0);
  sdrScale.setRotation(PI/2, GControlMode.CORNER);
  sdrScale.setLimits(0.9, 0.1, 1.8);
  sdrScale.setEasing(20.0);
  sdrScale.setNumberFormat(G4P.DECIMAL, 2);
  sdrScale.setOpaque(false);
  sdrScale.addEventHandler(this, "sdrScale_change");
  label1 = new GLabel(this, 520, 20, 110, 20);
  label1.setText("Patrol To Follow");
  label1.setTextBold();
  label1.setOpaque(false);
  togGroup1 = new GToggleGroup();
  option1 = new GOption(this, 520, 40, 40, 20);
  option1.setText("1");
  option1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option1.setOpaque(false);
  option1.addEventHandler(this, "option1_clicked1");
  option2 = new GOption(this, 560, 40, 40, 20);
  option2.setText("2");
  option2.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option2.setOpaque(false);
  option2.addEventHandler(this, "option2_clicked1");
  option3 = new GOption(this, 600, 40, 40, 20);
  option3.setText("3");
  option3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option3.setOpaque(false);
  option3.addEventHandler(this, "option3_clicked1");
  option4 = new GOption(this, 520, 60, 40, 20);
  option4.setText("4");
  option4.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option4.setOpaque(false);
  option4.addEventHandler(this, "option4_clicked1");
  option5 = new GOption(this, 560, 60, 40, 20);
  option5.setText("5");
  option5.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option5.setOpaque(false);
  option5.addEventHandler(this, "option5_clicked1");
  option6 = new GOption(this, 600, 60, 40, 20);
  option6.setText("6");
  option6.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option6.setOpaque(false);
  option6.addEventHandler(this, "option6_clicked1");
  option7 = new GOption(this, 520, 80, 40, 20);
  option7.setText("7");
  option7.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option7.setOpaque(false);
  option7.addEventHandler(this, "option7_clicked1");
  option8 = new GOption(this, 560, 80, 40, 20);
  option8.setText("8");
  option8.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option8.setOpaque(false);
  option8.addEventHandler(this, "option8_clicked1");
  option9 = new GOption(this, 600, 80, 40, 20);
  option9.setText("9");
  option9.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option9.setOpaque(false);
  option9.addEventHandler(this, "option9_clicked1");
  option10 = new GOption(this, 540, 100, 80, 20);
  option10.setText("None");
  option10.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option10.setOpaque(false);
  option10.addEventHandler(this, "option10_clicked1");
  togGroup1.addControl(option1);
  togGroup1.addControl(option2);
  togGroup1.addControl(option3);
  togGroup1.addControl(option4);
  togGroup1.addControl(option5);
  togGroup1.addControl(option6);
  togGroup1.addControl(option7);
  togGroup1.addControl(option8);
  togGroup1.addControl(option9);
  togGroup1.addControl(option10);
  option10.setSelected(true);
  label2 = new GLabel(this, 520, 150, 120, 20);
  label2.setText("Frame Rate (fps)");
  label2.setTextBold();
  label2.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label2.setOpaque(false);
  lblFramerate = new GLabel(this, 520, 170, 110, 20);
  lblFramerate.setText("My label");
  lblFramerate.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  lblFramerate.setOpaque(false);
  label3 = new GLabel(this, 520, 220, 120, 20);
  label3.setText("World update time");
  label3.setTextBold();
  label3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label3.setOpaque(false);
  lblUpdateTime = new GLabel(this, 520, 240, 110, 20);
  lblUpdateTime.setText("My label");
  lblUpdateTime.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  lblUpdateTime.setOpaque(false);
  label4 = new GLabel(this, 520, 310, 60, 20);
  label4.setText("Buildings");
  label4.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label4.setOpaque(false);
  lblBuildings = new GLabel(this, 580, 310, 50, 20);
  lblBuildings.setText("???");
  lblBuildings.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblBuildings.setOpaque(false);
  label6 = new GLabel(this, 520, 290, 110, 20);
  label6.setText("World Statistics");
  label6.setTextBold();
  label6.setOpaque(false);
  label7 = new GLabel(this, 520, 330, 60, 20);
  label7.setText("Walls");
  label7.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label7.setOpaque(false);
  lblWalls = new GLabel(this, 580, 330, 50, 20);
  lblWalls.setText("???");
  lblWalls.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblWalls.setOpaque(false);
  label9 = new GLabel(this, 520, 350, 60, 20);
  label9.setText("People");
  label9.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label9.setOpaque(false);
  lblPeople = new GLabel(this, 580, 350, 50, 20);
  lblPeople.setText("???");
  lblPeople.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblPeople.setOpaque(false);
  label5 = new GLabel(this, 520, 390, 110, 20);
  label5.setText("Navigation Graph");
  label5.setTextBold();
  label5.setOpaque(false);
  label8 = new GLabel(this, 520, 410, 60, 20);
  label8.setText("Nodes");
  label8.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label8.setOpaque(false);
  lblNodes = new GLabel(this, 580, 410, 50, 20);
  lblNodes.setText("???");
  lblNodes.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblNodes.setOpaque(false);
  label11 = new GLabel(this, 520, 430, 60, 20);
  label11.setText("Edges");
  label11.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label11.setOpaque(false);
  lblEdges = new GLabel(this, 580, 430, 50, 20);
  lblEdges.setText("???");
  lblEdges.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lblEdges.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GSlider sdrScale; 
GLabel label1; 
GToggleGroup togGroup1; 
GOption option1; 
GOption option2; 
GOption option3; 
GOption option4; 
GOption option5; 
GOption option6; 
GOption option7; 
GOption option8; 
GOption option9; 
GOption option10; 
GLabel label2; 
GLabel lblFramerate; 
GLabel label3; 
GLabel lblUpdateTime; 
GLabel label4; 
GLabel lblBuildings; 
GLabel label6; 
GLabel label7; 
GLabel lblWalls; 
GLabel label9; 
GLabel lblPeople; 
GLabel label5; 
GLabel label8; 
GLabel lblNodes; 
GLabel label11; 
GLabel lblEdges; 

