/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clab_artoolkit_port_JARParameter */

#ifndef _Included_com_clab_artoolkit_port_JARParameter
#define _Included_com_clab_artoolkit_port_JARParameter
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_clab_artoolkit_port_JARParameter
	* Method:    JARParamChangeSize
	* Signature: (II)I
	*/
	JNIEXPORT jint JNICALL Java_com_clab_artoolkit_port_JARParameter_JARParamChangeSize
		(JNIEnv *, jobject, jint, jint);

	/*
	* Class:     com_clab_artoolkit_port_JARParameter
	* Method:    JARParamLoad
	* Signature: (Ljava/lang/String;)I
	*/
	JNIEXPORT jint JNICALL Java_com_clab_artoolkit_port_JARParameter_JARParamLoad
		(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
